PostPita/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PostPita.Data;
using PostPita.Models;

namespace PostPita.Controllers
{
    [Authorize(Roles = "Company")]
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IPostRep _postRep;

        public PostsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IPostRep postRep)
        {
            _context = context;
            _userManager = userManager;
            _postRep = postRep;

        }

        public async Task<IActionResult> Index()
        {
            var appUser = await _userManager.GetUserAsync(User);
            var user = await _context.CompanyUsers.SingleOrDefaultAsync(u => u.User == appUser);
            //ViewBag.CompanyName = user.CoName;
            var posts = await _context.Posts.Where(p => p.Company == user).ToListAsync();
            posts.Reverse();
            return View(posts);
        }

        public async Task<IActionResult> AllApplicant()
        {
            var appUser = await _userManager.GetUserAsync(User);
            var user = await _context.CompanyUsers.SingleOrDefaultAsync(u => u.User == appUser);

            var applicants = await _postRep.GetAllApplicantAsync(user);
            applicants.Reverse();
            return View(applicants);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.SingleOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            var app = await _postRep.GetApplicant(post);
            var t = new Tuple<Post, List<Applicant>>(post, app);

            return View(t);
        }

        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
                return View();
            var post = await _context.Posts.SingleOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return View();
            }

            return View(new PostVM(post));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PostVM postVm)
        {
            if (ModelState.IsValid)
            {
                var usera = await _userManager.GetUserAsync(User);
                var user = await _context.CompanyUsers.SingleOrDefaultAsync(u => usera == u.User);
                _context.Posts.Add(new Post(postVm, user) { PostStatus = PostStatus.Wait, PostingTime = DateTime.Now });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(postVm);
        }

        public async Task<IActionResult> Hide(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.SingleOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(User);
            if (user.CompanyUser != post.Company)
                return RedirectToAction("AccessDenied", "Account");

            if (post.PostStatus != PostStatus.Approved)
            {
                return BadRequest();
            }
            post.PostStatus = PostStatus.Hidden;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Show(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.SingleOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(User);
            if (user.CompanyUser != post.Company)
                return RedirectToAction("AccessDenied", "Account");

            if (post.PostStatus != PostStatus.Hidden)
            {
                return BadRequest();
            }
            post.PostStatus = PostStatus.Approved;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Review(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.SingleOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(User);
            if (user.CompanyUser != post.Company)
                return RedirectToAction("AccessDenied", "Account");

            if (post.PostStatus != PostStatus.Rejected)
            {
                return BadRequest();
            }
            post.PostStatus = PostStatus.Review;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .SingleOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.Include(a => a.Applicants).SingleOrDefaultAsync(m => m.Id == id);

            _context.Applicants.RemoveRange(post.Applicants);
            _context.Posts.Remove(post);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.Id == id);
        }

        public async Task<IActionResult> addInBlackList(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicant = await _context.Applicants.SingleOrDefaultAsync(m => m.Id == id);
            if (applicant == null)
            {
                return NotFound();
            }

            applicant.isInBlackList = true;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var post = await _context.Posts.SingleOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            //if (post.PostStatus != PostStatus.Approved)
            //{
            //    return BadRequest();
            //}

            var user = await _userManager.GetUserAsync(User);
            if (user.CompanyUser != post.Company)
            {
                return RedirectToAction("AccessDenied", "Account");
            }

            return View(new PostVM(post));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int? id, [FromForm]PostVM postVm)
        {
            var user = await _userManager.GetUserAsync(User);
            var post = await _context.Posts.Include(p => p.Modified).SingleOrDefaultAsync(m => m.Id == id);
            if (user.CompanyUser != post.Company)
            {
                return RedirectToAction("AccessDenied", "Account");
            }

            //if (post.PostStatus != PostStatus.Approved)
            //{
            //    return BadRequest();
            //}

            if (ModelState.IsValid)
            {
                if (post.Modified == null)
                {
                    _context.PostsModified.Add(new PostModified(postVm, post));
                }
                else
                {
                    var p2 = await _context.PostsModified.SingleOrDefaultAsync(a => a == post.Modified);

                    _context.PostsModified.Remove(p2);
                    _context.SaveChanges();
                    _context.PostsModified.Add(new PostModified(postVm, post));

                }

                post.PostStatus = PostStatus.Modified;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(postVm);
        }


    }
}

PostPita/Views/Shared/_Layout2.cshtml
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/toastr.min.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    @*<link rel="stylesheet" type="text/css" href="~/css/searchpage.css">*@

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700|Roboto:100,300,400,500,700"
          rel="stylesheet">
</head>
<body>
    <!-- header section start -->
    <div class="container-fluid headerSection">
        <!-- navbar start -->
        <div class="row">
            <nav class="navbar navbar-expand-lg navbar-light w-100 px-5 py-3">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/assets/img/paljobs.png">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    @if (User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Administer" asp-action="Index">Administer Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Manage" asp-action="Notifications">Notification</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Search" asp-action="Index">Search Page</a>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post">
                                    <button type="submit" class="btn btn-link nav-link">Logout</button>
                                </form>
                            </li>
                        </ul>
                    }
                    else if (User.IsInRole("Company"))
                    {
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Posts" asp-action="Create">Manage</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Manage" asp-action="Notifications">Notification</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Search" asp-action="Index">Search</a>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post">
                                    <button type="submit" class="btn btn-link nav-link">Logout</button>
                                </form>
                            </li>
                        </ul>
                    }
                    else if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Manage" asp-action="Index">Hello @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Manage" asp-action="Notifications">Notification</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Search" asp-action="Index">Search</a>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post">
                                    <button type="submit" class="btn btn-link nav-link">Logout</button>
                                </form>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Search" asp-action="Index">explore</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="About">about</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Contact">contact</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="ComRegister" class="nav-link">Company</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="EmpRegister" class="nav-link">Applicant</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Login" class="nav-link">Login</a>
                            </li>
                        </ul>
                    }
                    <form class="form-inline searching ml-lg-4 mt-3 mt-lg-0" action="">
                        <div class="form-group">
                            <input type="search" placeholder="Search" class="form-control">
                            <button type="submit" id="testAjax" class="searchBtn">
                                <i class='fas fa-search'></i>
                            </button>
                        </div>
                    </form>
                </div>
            </nav>
        </div>
        <!-- navbar end -->
    </div>
    <!-- header section end -->
    <!-- mainSection -->
    @RenderBody()
    <!-- mainSection -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="~/assets/js/jquery3.3.1.js"></script>
    <script src="~/assets/js/popper.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/toastr.min.js"></script>
    <script src="~/assets/js/main.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>

PostPita/Views/Shared/_Layout4.cshtml
@{
    Layout = null;
}
@using Microsoft.EntityFrameworkCore
@using PostPita.Data
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
@inject ApplicationDbContext Context

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" type="text/css" href="~/css/searchpage.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<body>
    <!--start_NavBar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            @if (SignInManager.IsSignedIn(User) && User.IsInRole("Company"))
            {
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    @((await Context.Users
                                       .Include(u => u.CompanyUser)
                                       .SingleOrDefaultAsync(u => u.UserName == User.Identity.Name))
                                       .CompanyUser.CoName)
                </a>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img src="data:image/png;base64,
                   @((await Context.Users
                         .Include(u => u.CompanyUser)
                         .SingleOrDefaultAsync(u => u.UserName == User.Identity.Name))
                         .CompanyUser.Logo)" width="20" height="20" />
                </a>
            }
            else
            {
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand" style="margin-left: 2%;">PostPita</a>
            }

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                @if (User.IsInRole("Admin"))
                {
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a asp-area="" asp-controller="Administer" asp-action="Index" class="nav-link">AdministerPage</a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Manage" asp-action="Notifications" class="nav-link">Notification</a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Search" asp-action="Index" class="nav-link">Search</a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                        </li>
                        @* <li class="nav-item"> *@
                        @*     <a asp-area="" asp-controller="Home" asp-action="About" class="nav-link">About</a> *@
                        @* </li> *@
                        @* <li class="nav-item"> *@
                        @*     <a asp-area="" asp-controller="Home" asp-action="Contact" class="nav-link">Contact</a> *@
                        @* </li> *@
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Manage" asp-action="Notifications" class="nav-link">Notification</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Search" asp-action="Index" class="nav-link">Search</a>
                        </li>
                    </ul>
                }
                @if (User.IsInRole("Company"))
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Manage" asp-action="Index" title="Manage" class="nav-link">@UserManager.GetUserName(User)!</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Manage
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Ratings" asp-action="Index">Rating Manage</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Posts" asp-action="Index">Post Manage</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="form-inline">
                                <button type="submit" class="btn btn-outline-dark">Logout</button>
                            </form>
                        </li>
                    </ul>
                }
                else if (SignInManager.IsSignedIn(User))
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Manage" asp-action="Index" title="Manage" class="nav-link">@UserManager.GetUserName(User)!</a>
                        </li>
                        <li class="nav-item">
                            <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="form-inline">
                                <button type="submit" class="btn nav-item">Logout</button>
                            </form>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Account" asp-action="ComRegister" class="nav-link">Company</a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Account" asp-action="EmpRegister" class="nav-link">Applicant</a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Account" asp-action="Login" class="nav-link">Login</a>
                        </li>
                    </ul>
                }

            </div>
        </div>
    </nav>
    <!--end_navBar-->


    <div class="container body-content">
        @RenderBody()
    </div>

    <!--start_footer-->
    <footer>
        <div class="row">
            <div class="offset-md-1 col-md-2 ">
                <ul>
                    <li><a href="">About Us</a></li>
                    <li><a href="">Concat</a></li>
                    <li><a href="">Team</a></li>

                </ul>
            </div>
            <div class="col-md-3 ">
                <ul>
                    <li><i class="fab fa-facebook-f"></i><a href="">FaceBook</a></li>
                    <li><i class="fab fa-twitter"></i><a href="">Twitter</a></li>
                    <li><i class="fab fa-instagram"></i><a href="">Instagram</a></li>
                </ul>
            </div>
            <div class="col-md-3 ">
                <ul>
                    <li>Send Email:</li>
                    <li>
                        <form>
                            <input type="Email" class="form-control" placeholder="Enter Email" style="width: 150px;display:inline-block;" name="">
                            <input type="submit" value="ok" class="btn btn-light" style="background-color: white;color:#1093c5" name="">
                        </form>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 ">
                <ul>
                    <li>Palestine,GAZA</li>
                    <li>2683949</li>
                    <li>Ahmed@hotmail.com</li>
                </ul>
            </div>
        </div>
    </footer>
    <!--end-footer-->



    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>



    @RenderSection("Scripts", required: false)
</body>
</html>

PostPita/Views/Shared/_LayoutCom.cshtml
@{
    Layout = "_Layout2";
}

<div class="container-fluid mainSectionJobs">
    <div class="row">
        <!-- side bar start-->
        <div class="sideBar col-3 px-0">
            <div class="nav  flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                <a class="nav-link" id="t1" asp-controller="Posts" asp-action="Create">Add a post</a>
                <a class="nav-link" id="t2" asp-controller="Posts" asp-action="Index">manage my jobs</a>
                <a class="nav-link" id="t3" asp-controller="Posts" asp-action="AllApplicant">manage applicants</a>
                <a class="nav-link" id="t4" asp-controller="Ratings" asp-action="Create">rate an applicant</a>
                <a class="nav-link" id="t5" asp-controller="Ratings" asp-action="Index">view ratings</a>
                <a class="nav-link" id="t6" asp-controller="Manage" asp-action="ChangePasswordCom">change password</a>
            </div>
        </div>
        <!-- side bar end-->

        <div class="tabContentContainer w-100 offset-3">
            <div class="tab-content" id="v-pills-tabContent">
                <!-- tab-content -->
                @RenderBody()
                <!-- tab-content -->
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @RenderSection("Scripts", required: false)
}